// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2);
}

export function AddNode(arg1, arg2) {
  return window['go']['main']['App']['AddNode'](arg1, arg2);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ClickAt(arg1, arg2) {
  return window['go']['main']['App']['ClickAt'](arg1, arg2);
}

export function FocusChat() {
  return window['go']['main']['App']['FocusChat']();
}

export function GetWindowInfo() {
  return window['go']['main']['App']['GetWindowInfo']();
}

export function MoveTo(arg1, arg2) {
  return window['go']['main']['App']['MoveTo'](arg1, arg2);
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SwitchC4Level(arg1) {
  return window['go']['main']['App']['SwitchC4Level'](arg1);
}

export function ToggleChat() {
  return window['go']['main']['App']['ToggleChat']();
}
