// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddConnection(arg1:string,arg2:main.Connection):Promise<string>;

export function AddNode(arg1:string,arg2:main.DiagramNode):Promise<string>;

export function Chat(arg1:string):Promise<string>;

export function ClickAt(arg1:number,arg2:number):Promise<void>;

export function FocusChat():Promise<void>;

export function GetWindowInfo():Promise<Record<string, any>>;

export function MoveTo(arg1:number,arg2:number):Promise<void>;

export function SendChatMessage(arg1:string):Promise<void>;

export function SwitchC4Level(arg1:string):Promise<void>;

export function ToggleChat():Promise<void>;
